# Generated by Django 3.1.2 on 2021-11-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='Selected_Truck',
            field=models.CharField(default='', max_length=100),
        ),
    ]
