# Generated by Django 3.1.2 on 2021-11-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_searchdata_selected_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='user_contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
