# Generated by Django 3.1.2 on 2021-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_searchdata_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='distance',
            field=models.CharField(default='', max_length=100),
        ),
    ]
