# Generated by Django 3.1.2 on 2021-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_searchdata_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='booking_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
