# Generated by Django 3.1.2 on 2021-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_searchdata_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro', models.CharField(max_length=100)),
                ('mini', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('max', models.CharField(max_length=100)),
                ('ultramax', models.CharField(max_length=100)),
            ],
        ),
    ]
