# Generated by Django 3.1.2 on 2021-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211117_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='Truck_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
