# Generated by Django 3.1.2 on 2021-11-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_searchdata_truck_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchdata',
            old_name='Truck_type',
            new_name='Trucktype',
        ),
    ]
