# Generated by Django 3.1.2 on 2021-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211118_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrate',
            name='Rate',
            field=models.IntegerField(),
        ),
    ]
