# Generated by Django 3.1.2 on 2021-01-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_content',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('blog_type', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=200)),
                ('blog_thumbnail', models.ImageField(upload_to='static/image/A_blog')),
                ('content', models.TextField()),
            ],
        ),
    ]
