# Generated by Django 3.1.2 on 2021-02-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('A_driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser_adriver',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Adding_Driver_details',
            fields=[
                ('D_Si_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=150)),
                ('Email', models.CharField(default='', max_length=250)),
                ('Phone_1', models.CharField(default='', max_length=13)),
                ('Phone_2', models.CharField(default='', max_length=13)),
                ('Street_no', models.CharField(default='', max_length=100)),
                ('Address_1', models.CharField(default='', max_length=250)),
                ('Address_2', models.CharField(default='', max_length=250)),
                ('Zip_code', models.CharField(default='', max_length=150)),
                ('District', models.CharField(blank=True, max_length=150)),
                ('State', models.CharField(blank=True, max_length=150)),
                ('Nationality', models.CharField(blank=True, max_length=150)),
                ('Bank_account', models.CharField(default='', max_length=150)),
                ('Bank_account_user_name', models.CharField(default='', max_length=150)),
                ('Ifsc_code', models.CharField(default='', max_length=150)),
                ('Bank_name', models.CharField(default='', max_length=150)),
                ('Pan_no', models.CharField(default='', max_length=150)),
                ('Aadhar_no', models.CharField(default='', max_length=150)),
                ('User_picture', models.FileField(upload_to='static/file/A_driver')),
                ('Aadhar_copy', models.FileField(upload_to='static/file/A_driver')),
                ('Pan_copy', models.FileField(upload_to='static/file/A_driver')),
                ('DrivingLisence_copy', models.FileField(upload_to='static/file/A_driver')),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
