# Generated by Django 3.1.2 on 2021-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_driver', '0002_auto_20210220_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='adding_driver_details',
            name='Adriver_profile_id',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adding_driver_details',
            name='DrivingLisence_no',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='adding_driver_details',
            name='driving_truck_type',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
