# Generated by Django 3.1.2 on 2021-02-19 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser_Abusniess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_phone', models.CharField(default='', max_length=15)),
                ('signup_email', models.CharField(default='', max_length=15)),
                ('signup_username', models.CharField(default='', max_length=15)),
                ('user_x', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adding_truck_details',
            fields=[
                ('Si_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=150)),
                ('Email', models.CharField(default='', max_length=250)),
                ('Phone_1', models.CharField(default='', max_length=13)),
                ('Phone_2', models.CharField(default='', max_length=13)),
                ('Street_no', models.CharField(default='', max_length=100)),
                ('Address_1', models.CharField(default='', max_length=250)),
                ('Address_2', models.CharField(default='', max_length=250)),
                ('Zip_code', models.CharField(default='', max_length=150)),
                ('District', models.CharField(blank=True, max_length=150)),
                ('State', models.CharField(blank=True, max_length=150)),
                ('Nationality', models.CharField(blank=True, max_length=150)),
                ('Bank_account', models.CharField(default='', max_length=150)),
                ('Ifc_code', models.CharField(default='', max_length=150)),
                ('Bank_name', models.CharField(default='', max_length=150)),
                ('Pan_no', models.CharField(default='', max_length=150)),
                ('Aadhar_no', models.CharField(default='', max_length=150)),
                ('Truck_type', models.CharField(blank=True, max_length=150)),
                ('Vehicle_company', models.CharField(default='', max_length=150)),
                ('Vehicle_model', models.CharField(default='', max_length=150)),
                ('Chechis_no', models.CharField(default='', max_length=150)),
                ('Engine_no', models.CharField(default='', max_length=150)),
                ('Registration_no', models.CharField(default='', max_length=150)),
                ('Front_img', models.FileField(upload_to='static/file/A_business')),
                ('Left_img', models.FileField(upload_to='static/file/A_business')),
                ('Right_img', models.FileField(upload_to='static/file/A_business')),
                ('Pan_card', models.FileField(upload_to='static/file/A_business')),
                ('Aadhar_card', models.FileField(upload_to='static/file/A_business')),
                ('Polluton_receipt', models.FileField(upload_to='static/file/A_business')),
                ('Insurence', models.ImageField(upload_to='static/file/A_business')),
                ('Fitness_certificare', models.ImageField(upload_to='static/file/A_business')),
                ('Tax_receipts', models.FileField(upload_to='static/file/A_business')),
                ('Permit', models.FileField(upload_to='static/file/A_business')),
                ('Rc_certificate', models.FileField(upload_to='static/file/A_business')),
                ('Search', models.SlugField(default='', max_length=150)),
                ('pyment_Details', models.SlugField(default='', max_length=150)),
                ('Penalty', models.SlugField(default='', max_length=150)),
                ('View_details', models.SlugField(default='', max_length=150)),
                ('Edit_details', models.SlugField(default='', max_length=150)),
                ('Remove_truck', models.SlugField(default='', max_length=150)),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
