# Generated by Django 3.1.2 on 2021-03-23 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('A_business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser_abusniess',
            name='signup_email',
        ),
        migrations.RemoveField(
            model_name='extendeduser_abusniess',
            name='signup_phone',
        ),
        migrations.RemoveField(
            model_name='extendeduser_abusniess',
            name='signup_username',
        ),
        migrations.AddField(
            model_name='extendeduser_abusniess',
            name='Latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='extendeduser_abusniess',
            name='Longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='extendeduser_abusniess',
            name='Speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='extendeduser_abusniess',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
