# Generated by Django 3.1.2 on 2021-10-25 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('A_business', '0003_auto_20210323_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adding_truck_details',
            old_name='Aadhar_no',
            new_name='Abusiness_profile_id',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Aadhar_card',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Address_1',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Address_2',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Bank_account',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Bank_name',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='District',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Edit_details',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Ifc_code',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Left_img',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Nationality',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Pan_card',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Pan_no',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Penalty',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Phone_1',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Phone_2',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Remove_truck',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Right_img',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Search',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='State',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Street_no',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='View_details',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='Zip_code',
        ),
        migrations.RemoveField(
            model_name='adding_truck_details',
            name='pyment_Details',
        ),
        migrations.CreateModel(
            name='Adding_truck_with_driver',
            fields=[
                ('Si_no', models.AutoField(primary_key=True, serialize=False)),
                ('Truck_type', models.CharField(blank=True, max_length=150)),
                ('Vehicle_company', models.CharField(default='', max_length=150)),
                ('Vehicle_model', models.CharField(default='', max_length=150)),
                ('Chechis_no', models.CharField(default='', max_length=150)),
                ('Engine_no', models.CharField(default='', max_length=150)),
                ('Registration_no', models.CharField(default='', max_length=150)),
                ('Abusiness_profile_id', models.CharField(default='', max_length=150)),
                ('Adriver_profile_id', models.CharField(default='', max_length=150)),
                ('Front_img', models.FileField(upload_to='static/file/A_business')),
                ('Polluton_receipt', models.FileField(upload_to='static/file/A_business')),
                ('Insurence', models.ImageField(upload_to='static/file/A_business')),
                ('Fitness_certificare', models.ImageField(upload_to='static/file/A_business')),
                ('Tax_receipts', models.FileField(upload_to='static/file/A_business')),
                ('Permit', models.FileField(upload_to='static/file/A_business')),
                ('Rc_certificate', models.FileField(upload_to='static/file/A_business')),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adding_Abusiness_profile',
            fields=[
                ('Si_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=150)),
                ('Email', models.CharField(default='', max_length=250)),
                ('Phone_1', models.CharField(default='', max_length=13)),
                ('Phone_2', models.CharField(default='', max_length=13)),
                ('Street_no', models.CharField(default='', max_length=100)),
                ('Address_1', models.CharField(default='', max_length=250)),
                ('Address_2', models.CharField(default='', max_length=250)),
                ('Zip_code', models.CharField(default='', max_length=150)),
                ('District', models.CharField(blank=True, max_length=150)),
                ('State', models.CharField(blank=True, max_length=150)),
                ('Nationality', models.CharField(blank=True, max_length=150)),
                ('Bank_account', models.CharField(default='', max_length=150)),
                ('Ifc_code', models.CharField(default='', max_length=150)),
                ('Bank_name', models.CharField(default='', max_length=150)),
                ('Acount_holder_name', models.CharField(default='', max_length=150)),
                ('Pan_no', models.CharField(default='', max_length=150)),
                ('Aadhar_no', models.CharField(default='', max_length=150)),
                ('Driving_Truck_type', models.CharField(blank=True, max_length=150)),
                ('Driving_license_no', models.CharField(blank=True, max_length=150)),
                ('Profile_id', models.CharField(blank=True, max_length=250)),
                ('user_img', models.FileField(upload_to='static/file/A_business')),
                ('copy_od_pan', models.FileField(upload_to='static/file/A_business')),
                ('copy_of_aadhar', models.FileField(upload_to='static/file/A_business')),
                ('copy_of_license', models.FileField(upload_to='static/file/A_business')),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
