# Generated by Django 3.1.2 on 2021-10-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_business', '0004_auto_20211025_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adding_abusiness_profile',
            old_name='copy_od_pan',
            new_name='copy_of_pan',
        ),
    ]
