# Generated by Django 3.1.2 on 2021-10-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_business', '0005_auto_20211025_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adding_abusiness_profile',
            old_name='Profile_id',
            new_name='B_Profile_id',
        ),
        migrations.AddField(
            model_name='adding_abusiness_profile',
            name='D_Profile_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
